### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by kevkid** [qdot/VaMSync#2]
I have been trying to get this to work for some time and there seems to be a lack of documentation on any of this stuff?
I have VAM and vamsync connected, I also have my device connected. I can load the plugin into a scene by going to edit mode -> selecting an atom (such as a person) -> then selecting a control -> then selecting root -> plugins -> adding the plugin. But some of the atoms (like for a person) doesnt move, but their controls do such as hips or pelvis. But I can't link vamsync to this control? How does this work? Do I need special scenes? can you please point me in the right direction? Thank you.

**Comment by kevkid** [comment]
I figured it out

**Comment by gino8080** [comment]
can you please explain how do you solved?

**Comment by gino8080** [comment]
> I figured it out

please can you give me some hints?
